### PR TITLE
fix: replace deprecated Boom.wrap call

### LINKED ISSUE #20: BUG: Boom removed wrap function in 7.0.0
The module throws an error because `Boom.wrap()` is not a function anymore

## Description
According to `@hapi/boom` [changelog](https://hapi.dev/module/boom/changelog/), they removed the `wrap` function in v7.0.0 https://github.com/hapijs/boom/issues/171. This module is using v10.0.0

## Expected Behavior
The `errorMiddleware` dispatches the error without any issue

## Actual Behavior
The module throws an error when executing `Boom.wrap()` in the `errorMiddleware` function

## Possible Fix
According to their documentation, I think `boomify(err, [options])` might have replaced `wrap(err)`

## Steps to Reproduce
I have this endpoint:

```js
app.post(
      '/v1/subscriptions/:subscriptionId/cancel',
      keycloak.protect(),
      (req, res, next) => {
        const { subscriptionId } = req.params;
        controllerApi.cancelSubscription(subscriptionId)
          .then(() => res.json({
            statusCode: 200,
          }))
          .catch(err => next(err));
      },
    )
```

Where `keycloak.protect()` is a middleware function from `keycloak-connect`, intended to validate the input token. Validation passes, but `controllerApi.cancelSubscription` throws. After that, I get:

```
TypeError: Boom.wrap is not a function
  at errorMiddleware (/path/to/node_modules/systemic-express/lib/default-middleware.js:36:20)
  at Layer.handle_error (/path/to/node_modules/express/lib/router/layer.js:71:5)
  at trim_prefix (/path/to/node_modules/express/lib/router/index.js:326:13)
  at /path/to/node_modules/express/lib/router/index.js:286:9
  at Function.process_params (/path/to/node_modules/express/lib/router/index.js:346:12)
  at next (/path/to/node_modules/express/lib/router/index.js:280:10)
  at Layer.handle_error (/path/to/node_modules/express/lib/router/layer.js:67:12)
  at trim_prefix (/path/to/node_modules/express/lib/router/index.js:326:13)
  at /path/to/node_modules/express/lib/router/index.js:286:9
  at Function.process_params (/path/to/node_modules/express/lib/router/index.js:346:12)
```

## Context
I'm just using a regular express handler which may throw an error after an external call. When it does throw, I get the `TypeError: Boom.wrap is not a function` error

## Your Environment

* Version used: 1.1.3 (and `systemic` 3.3.7)
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 16
* Operating System and version (desktop or mobile): 
* Link to your project:

### PR DESCRIPTION
**Pull request by LonelyPrincess**
### Main changes

- :bug: (fix)

### Additional notes

This PR resolves #20, which relates to the following error that sometimes show up when using this module:

```
TypeError: Boom.wrap is not a function
    at errorMiddleware (C:\Development\app-he-hoges-web\node_modules\systemic-express\lib\default-middleware.js:36:20)
    at Layer.handle_error (C:\Development\app-he-hoges-web\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Development\app-he-hoges-web\node_modules\express\lib\router\index.js:326:13)
    at C:\Development\app-he-hoges-web\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Development\app-he-hoges-web\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Development\app-he-hoges-web\node_modules\express\lib\router\index.js:280:10)
    at Layer.handle_error (C:\Development\app-he-hoges-web\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\Development\app-he-hoges-web\node_modules\express\lib\router\index.js:326:13)
    at C:\Development\app-he-hoges-web\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Development\app-he-hoges-web\node_modules\express\lib\router\index.js:346:12)
```

This issue was pressumably introduced in #13, which upgraded the `boom` package from [version 3.2.2 to 10.0.0](https://github.com/hapijs/boom/compare/v3.2.2...v10.0.0). `Boom.wrap` has long became deprecated and replaced by `Boom.boomify`.

This also replaces the `logger.log` calls in the default error middleware which were causing this exception and the errors not to properly be displayed:

```
TypeError: logger.log is not a function
    at errorMiddleware (C:\Development\app-he-hoges-web\node_modules\systemic-express\lib\default-middleware.js:42:73)
```

### CODE REVIEW

**Comment by Polpetta** [comment]
I've got to say, this fix is very useful. I ended up encountering this many times, and after trying out this branch the errors are now clear and it is possible to properly debug. I highly recommend approving this PR and releasing a new version of this package!

Thanks to @LonelyPrincess for tackling down this problem and fixing it 💯🎉

**Review by bounteous17 — APPROVED** [review]
